version: '2'

networks:
  main:

services:
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=vendas_api
    ports:
      - "3306:3306"
    volumes:
      - /path/to/mariadb-persistence:/var/lib/bitnami/mariadb
    networks:
      main:

  vendas:
    tty: true
    container_name: vendas
    image: docker.io/bitnami/laravel:8
    environment:
      - ENV_ALIAS=dev
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_DATABASE=vendas_api
      - DB_PASSWORD=
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      main:
    privileged: true # Privileged mode could be required to run this container under Windows
